CREATE TABLE IF NOT EXISTS packages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    branch VARCHAR(255) NOT NULL,
    arch VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    epoch INT NOT NULL DEFAULT 0,
    version VARCHAR(255) NOT NULL,
    release VARCHAR(255) NOT NULL,
    disttag VARCHAR(255),
    buildtime BIGINT NOT NULL DEFAULT 0,
    source VARCHAR(255)
);